country_mapping = {
    'Česká republika': 'Czech Republic',
    'Itálie': 'Italy',
    'Slovensko': 'Slovakia',
    'Kanada': 'Canada',
    'Německo': 'Germany',
    'Peru': 'Peru',
    'Bulharsko': 'Bulgaria',
    'Polsko': 'Poland',
    'Rakousko': 'Austria',
    'Švýcarsko': 'Switzerland',
    'Maďarsko': 'Hungary',
    'Ukrajina': 'Ukraine',
    'Francie': 'France',
    'Rusko': 'Russian Federation',
    'Uganda': 'Uganda',
    'Srbsko': 'Serbia',
    'Španělsko': 'Spain',
    'Bosna a Hercegovina': 'Bosnia and Herzegovina',
    'Spojené státy': 'United States',
    'Spojené království': 'United Kingdom',
    'Nizozemsko': 'Netherlands',
    'Slovinsko': 'Slovenia',
    'Chorvatsko': 'Croatia',
    'Izrael': 'Israel',
    'Estonsko': 'Estonia',
    'Argentina': 'Argentina',
    'Rumunsko': 'Romania',
    'Lotyšsko': 'Latvia',
    'Irsko': 'Ireland',
    'Belgie': 'Belgium',
    'Zambie': 'Zambia',
    'Švédsko': 'Sweden',
    'Chile': 'Chile',
    'Cookovy ostrovy': 'Cook Islands',
    'Jihoafrická republika': 'South Africa',
    'Japonsko': 'Japan',
    'Dánsko': 'Denmark',
    'Austrálie': 'Australia',
    'Mexiko': 'Mexico',
    'Egypt': 'Egypt',
    'Litva': 'Lithuania',
    'Brazílie': 'Brazil',
    'Bělorusko': 'Belarus',
    'Irák': 'Iraq',
    'Korea': 'Republic of Korea',
    'Tunisko': 'Tunisia',
    'Portugalsko': 'Portugal',
    'Monako': 'Monaco',
    'Řecko': 'Greece',
    'Vietnam': 'Viet Nam',
    'Dominika': 'Dominica',
    'Gruzie': 'Georgia',
    'Nový Zéland': 'New Zealand',
    'Haiti': 'Haiti',
    'Alžírsko': 'Algeria',
    'Norsko': 'Norway',
    'Finsko': 'Finland',
    'Arménie': 'Armenia',
    'Kyrgyzstán': 'Kyrgyzstan',
    'Kuba': 'Cuba',
    'Turecko': 'Turkey',
    'Makedonie': 'Macedonia, the former Yugoslav Republic',
    'Černá Hora': 'Montenegro',
    'Filipíny': 'Philippines',
    'Venezuela': 'Venezuela',
    'Indie': 'India',
    'Kypr': 'Cyprus',
    'Etiopie': 'Ethiopia',
    'Uzbekistán': 'Uzbekistan',
    'Gibraltar': 'Gibraltar',
    'Réunion': 'Réunion',
    'Lichtenštejnsko': 'Liechtenstein',
    'Svatá Helena': 'Saint Helena',
    'Malta': 'Malta',
    'Panama': 'Panama',
    'Čína': 'China',
    'Sýrie': 'Syrian Arab Republic',
    'Moldavsko': 'Moldava, Republic of Moldava',
    'Albánie': 'Albania',
    'Uruguay': 'Uruguay',
    'Maroko': 'Morocco',
    'Jamajka': 'Jamaica',
    'Portoriko': 'Puerto Rico',
    'Kazachstán': 'Kazakhstan',
    'Bolívie': 'Bolivia',
    'Martinik': 'Martinique',
    'Senegal': 'Senegal',
    'Angola': 'Angola',
    'Trinidad a Tobago': 'Trinidad and Tobago',
    'Lucembursko': 'Luxembourg',
    'Britské panenské ostrovy': 'Virgin Islands, British',
    'Keňa': 'Kenya',
    'Írán': 'Iran, Islamic Republic of Iran',
    'Island': 'Iceland',
    'Spojené arabské emiráty': 'United Arab Emirates',
    'Madagaskar': 'Madagascar',
    'Tchaj-wan': 'Taiwan, Province of China',
    'Surinam': 'Suriname',
    'Dominikánská republika': 'Dominican Republic',
    'Indonésie': 'Indonesia',
    'Svatý stolec, Vatinkánský městský stát': 'Holy See, Vatican City State',
    'Ázerbájdžán': 'Azerbaijan',
    'Gabon': 'Gabon',
    'Bangladéš': 'Bangladesh',
    'Pákistán': 'Pakistan',
    'Kapverdy': 'Cape Verde',
    'Srí Lanka': 'Sri Lanka',
    'Podkarpatská Rus': 'Podkarpatská Rus',
    'Bahamy': 'Bahamas',
    'Paraguay': 'Paraguay',
    'Mali': 'Mali',
    'Zimbabwe': 'Zimbabwe',
    'Libanon': 'Lebanon',
    'Kolumbie': 'Colombia',
    'Singapur': 'Singapore',
    'Mongolsko': 'Mongolia',
    'Súdán': 'Sudan',
    'Palestina': 'Palestinian Territory, Occupied',
    'Kajmanské ostrovy': 'Cayman Islands',
    'Korea, lidově demokratická republika': 'Korea, Democratic Peoples Republic of Korea',
    'Malajsie': 'Malaysia',
    'Kambodža': 'Cambodia',
    'Tanzánie': 'Tanzania, United Republic of Tanzania',
    'Nigérie': 'Nigeria',
    'Ghana': 'Ghana',
    'Ekvádor': 'Ecuador',
    'Laos': 'Lao People Democratic Republic',
    'Libye': 'Libyan Arab Jamahiriya',
    'Seychely': 'Seychelles',
    'Thajsko': 'Thailand',
    'Guatemala': 'Guatemala',
    'Mosambik' : 'Mozambique',
    'Mauricius' : 'Mauritius',
    'Tádžikistán' : 'Tajikistan',
    'Guinea' : 'Guinea',
    'Guadeloupe' : 'Guadeloupe',
    'Americké panenské ostrovy' : 'Virgin Islands, U.S.',
    'Nikaragua' :'Nicaragua',
    'Myanmar' : 'Myanmar',
    'Kostarika' : 'Costa Rica',
    'Samoa' : 'Samoa',
    'Turkmenistán' : 'Turkmenistan',
    'Kosovo' : 'Kosovo',
    'Hongkong' :'Hong Kong',
    'Guyana' : 'Guyana',
    'Papua Nová Guinea' : 'Papua New Guinea',
    'Francouzská Guyana' : 'French Guiana',
    'Nizozemské Antily' :'Netherlands Antilles',
    'Kongo' : 'Congo',
    'Ostrov Man' : 'Isle of Man',
    'Jordánsko' : 'Jordan',
    'Namibie' : 'Namibia',
    'Britské indickooceánské území' : 'British Indian Ocean Territory',
    'Grónsko' : 'Greenland',
    'Jemen' : 'Yemen'
}

ethnicity_mapping = {
    'česká': 'Czechs',
    'slovenská': 'Slovaks',
    'německá': 'Germans',
    'ukrajinská': 'Ukrainians',
    'maďarská': 'Hungarians',
    'korejská': 'Koreans',
    'rakouská': 'Austrians',
    'polská': 'Poles',
    'srbská': 'Serbians',
    'francouzská': 'French',
    'ruská': 'Russians',
    'židovská': 'Jewish',
    'italská': 'Italians',
    'španělská': 'Spanish',
    'americká': 'Americans',
    'belgická': 'Belgians',
    'slovinská': 'Slovenians',
    'estonská': 'Estonians',
    'rumunská': 'Romanians',
    'holandská': 'Dutch',
    'irská': 'Irish',
    'anglická': 'English',
    'kanadská': 'Canadians',
    'japonská': 'Japanese',
    'chorvatská': 'Croatians',
    'argentinská': 'Argentinians',
    'dánská': 'Danes',
    'skotská': 'Scots',
    'čínská': 'Chinese',
    'švýcarská': 'Swiss',
    'bulharská': 'Bulgarians',
    'vlámská': 'Flemish',
    'chilská': 'Chileans',
    'mexická': 'Mexicans',
    'litevská': 'Lithuanians',
    'běloruská': 'Belarusians',
    'irácká': 'Iraqis',
    'řecká': 'Greeks',
    'vietnamská': 'Vietnamese',
    'norská': 'Norwegians',
    'kubánská': 'Cubans',
    'makedonská': 'Macedonians',
    'švédská': 'Swedes',
    'venezuelská': 'Venezuelans',
    'indická': 'Indians',
    'palestinská': 'Palestinians',
    'lotyšská': 'Latvians',
    'finská': 'Finns',
    'bosenská': 'Bosnians',
    'gruzínská': 'Georgians',
    'moravská': 'Moravians',
    'rusínská': 'Ruthenians',
    'moldavská': 'Moldovans',
    'albánská': 'Albanians',
    'arménská': 'Armenians',
    'portugalská': 'Portuguese',
    'brazilská': 'Brazilians',
    'romská': 'Romanis',
    'turecká': 'Turks',
    'mongolská': 'Mongolians',
    'katalánská': 'Catalans',
    'íránská': 'Iranians',
    'egyptská': 'Egyptians',
    'lužickosrbská': 'Sorbians',
    'uruguajská': 'Uruguayans',
    'australská': 'Australians',
    'velšská': 'Welsh',
    'islandská': 'Icelanders',
    'indonéská': 'Indonesians',
    'alžírská': 'Algerians',
    'kapverdská': 'Cape Verdeans',
    'novozélandská': 'New Zealanders',
    'rétorománská': 'Rhaeto-Romanics',
    'valónská': 'Walloon',
    'syrská': 'Syrians',
    'tuniská': 'Tunisians',
    'jamajská': 'Jamaicans',
    'kolumbijská': 'Colombians',
    'bolivijská': 'Bolivians',
    'peruánská': 'Peruvians',
    'portorická': 'Puerto Ricans',
    'paraguayská': 'Paraguayans',
    'jihoafrická': 'South Africans',
    'lucemburská': 'Luxembourgers',
    'tadžidská': 'Tajikistanis',
    'ekvádorská': 'Ecuadorians',
    'nigerijská': 'Nigerians',
    'keňská': 'Kenyans',
    'senegalská': 'Senegalese',
    'bangladéšská': 'Bangladeshis',
    'sudánská': 'Sudanese',
    'azerbájdžánská': 'Azerbaijanis',
    'filipínská': 'Filipinos',
    'nikaragujská': 'Nicaraguans',
    'jugoslávská': 'Yugoslavs',
    'libanonská': 'Lebanese',
    'kazašská': 'Kazakhstanis',
    'marocká': 'Moroccans'
}

sex_mapping = {
    'muž' : 'male',
    'žena': 'female',
    'jiné' : 'other'
}